#  Copyright (c) 2018 Thomas Heller
#
#  Distributed under the Boost Software License, Version 1.0. (See accompanying
#  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

.release-aarch64: &release-aarch64
    variables:
        CMAKE_BUILD_TYPE: "Release"
        CMAKE_EXTRA_FLAGS: "
            -DHPX_WITH_MALLOC=jemalloc
            -DHPX_WITH_GENERIC_CONTEXT_COROUTINES=On"
    tags:
        - linux
        - aarch64
        - gcc-7.3.0
        - boost-1.65.1

cmake Release aarch64:
    <<: *release-aarch64
    extends: .cmake

core Release aarch64:
    <<: *release-aarch64
    extends: .core
    dependencies:
        - checkout
        - cmake Release aarch64

examples Release aarch64:
    <<: *release-aarch64
    variables:
        TESTS: "examples"
    extends: .test
    dependencies:
        - checkout
        - core Release aarch64
        - get conv.xsl
        - get junit2html

tests.unit Release aarch64:
    <<: *release-aarch64
    variables:
        TESTS: "tests.unit"
    extends: .test
    dependencies:
        - checkout
        - core Release aarch64
        - get conv.xsl
        - get junit2html

tests.regressions Release aarch64:
    <<: *release-aarch64
    variables:
        TESTS: "tests.regressions"
    extends: .test
    dependencies:
        - checkout
        - core Release aarch64
        - get conv.xsl
        - get junit2html

tests.performance Release aarch64:
    <<: *release-aarch64
    variables:
        TESTS: "tests.performance"
    extends: .test
    dependencies:
        - checkout
        - core Release aarch64
        - get conv.xsl
        - get junit2html

tests.headers Release aarch64:
    <<: *release-aarch64
    variables:
        TESTS: "tests.headers"
    extends: .test
    dependencies:
        - checkout
        - core Release aarch64
        - get conv.xsl
